//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace PolygonSamples
{
    public sealed class SampleRectangle
    {   
        // The width of the object.
        private double widthValue;

        // The Width property for the object.
        public double Width { get { return this.widthValue; }  }
            
        // The height of the object.
        private double heightValue;

        // The Height property for the object.
        public double Height { get { return this.heightValue; }  }
                    
        public SampleRectangle(double width, double height)
        {
            this.widthValue = width;
            this.heightValue = height;
                        
        }
        
        // The Area property for the object.
        public double Area { get { return Width * Height; } }
        
        public override string ToString()
        {
            var result = string.Format("The rectangle object:\r\n Area = {0}", this.Area);
            result += string.Format("\r\n Width = {0}", Width);
            result += string.Format("\r\n Height = {0}", Height);
            return result;
        }
        
        public static void Main()
        {
            var testRectangle = new SampleRectangle(15.0D,10.0D);
            System.Console.WriteLine(testRectangle.ToString());
        }
    }
}