//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PolygonSamples
{
    using System;   
    
    public sealed class SampleTrapezoid
    {   
        // The shortBase of the object.
        private double shortBaseValue;

        // The ShortBase property for the object.
        public double ShortBase { get { return this.shortBaseValue; }  }
            
        // The longBase of the object.
        private double longBaseValue;

        // The LongBase property for the object.
        public double LongBase { get { return this.longBaseValue; }  }
            
        // The leftLeg of the object.
        private double leftLegValue;

        // The LeftLeg property for the object.
        public double LeftLeg { get { return this.leftLegValue; }  }
            
        // The rightLeg of the object.
        private double rightLegValue;

        // The RightLeg property for the object.
        public double RightLeg { get { return this.rightLegValue; }  }
                    
        public SampleTrapezoid(double shortBase, double longBase, double leftLeg, double rightLeg)
        {
            this.shortBaseValue = shortBase;
            this.longBaseValue = longBase;
            this.leftLegValue = leftLeg;
            this.rightLegValue = rightLeg;
            }
        
        // The Perimeter property for the object.
        public double Perimeter { get { return ShortBase + LongBase + LeftLeg + RightLeg; } }
        
        public override string ToString()
        {
            var result = $"The Trapezoid object:\r\n Perimeter = {this.Perimeter}";
            result += $"\r\n ShortBase = {ShortBase}";
            result += $"\r\n LongBase = {LongBase}";
            result += $"\r\n LeftLeg = {LeftLeg}";
            result += $"\r\n RightLeg = {RightLeg}";
            return result;
        }
        
        public static void Main()
        {
            var testTrapezoid = new SampleTrapezoid(20.0D,30.0D,13.0D,13.0D);
            System.Console.WriteLine(testTrapezoid.ToString());
        }
    }
}