//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ExcelCodeGen
{
    using System;

    public sealed class RectanglePolygon
    {
        // Attributes (fields)
        private double m_Width = 15.0;
        private double m_Height = 10.0;

        // Attributes (properties)
        public double Width { get { return this.m_Width; } }
        public double Height { get { return this.m_Height; } }

        // Derived attributes (co-properties)
        public double Diagonal { get { return Math.Sqrt(Math.Pow(Width, 2.0) + Math.Pow(Height, 2.0)); } }

        // Main values
        public double Area { get { return Width * Height; } }
        public double Perimeter { get { return 2 * Width + 2 * Height; } }

        public override string ToString()
        {
            // Polygon main values
            var result = $"The Rectangle object:\r\n   Area = {this.Area}\r\n   Perimeter = {this.Perimeter}";
            // Polygon main attributes
            result += "\r\n--------\r\n Main attributes:";
            result += $"\r\n   Width = {this.Width}";
            result += $"\r\n   Height = {this.Height}";
            // Polygon derived attributes
            result += "\r\n--------\r\n Derived attributes:";
            result += $"\r\n   Diagonal = {this.Diagonal}";
            return result;
        }

        public static void Main()
        {
            var polygon = new RectanglePolygon();

            System.Console.WriteLine(polygon.ToString());
        }
    }
}
